export function capitalize(value: string): string {
  if (!value) return '';
  return value.charAt(0).toUpperCase() + value.slice(1);
}
//# sourceMappingURL=format.js.map
// This file is generated by TypeScript and should not be edited directly. If you need to make changes, edit the corresponding .ts file and recompile.